import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import cp from "child_process";
import console from "console";
import { readFile, writeFile } from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Every file a real install needs in <vault>/.obsidian/plugins/obsidian42-brat/.
// main.js + manifest.json are required at the tarball root by the fork's
// extractor; styles.css is loaded automatically by Obsidian when present.
const DIST_FILES = ["main.js", "manifest.json", "styles.css"];

const prod = process.argv[2] === "production";
const watch = process.argv[3] !== "false" && !prod;

// Dev/watch convenience copies. Production writes dist/manifest.json itself
// and emitTarball() copies styles.css, so skip these in prod — under Bazel
// the copies would inherit the inputs' read-only mode and block the later
// writeFile of dist/manifest.json.
if (!prod) {
    fs.copyFile("manifest.json", "dist/manifest.json", (err) => {
        if (err) console.log(err);
    });
    fs.copyFile("styles.css", "dist/styles.css", (err) => {
        if (err) console.log(err);
    });
}

const context = await esbuild.context({
    banner: {
        js: banner
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outdir: "dist",
    metafile: true
});

if (prod || !watch) {
    const result = await context.rebuild();

    await writeFile("dist/meta.json", JSON.stringify(result.metafile, undefined, 2));
} else {
    await context.watch();
    process.exit(0);
}

// If dev lets make a dev manifest.json file.
const manifestFile = path.join("./manifest.json");
const data = await readFile(manifestFile, "utf-8");
const json = JSON.parse(data);

// Update version data.
json.version = prod
    ? `v${process.env.npm_package_version}`
    : `v${process.env.npm_package_version}-dev`;
await writeFile(path.join("dist", "manifest.json"), JSON.stringify(json, undefined, 2));

// Pack the release tarball this very fork prefers when installing plugins:
// it needs main.js + manifest.json at the archive root and installs every
// file the archive contains (see MonoParra/PACKAGE.md). BRAT updates itself
// through the same path, so ship one for ourselves too.
if (prod) {
    console.log(`dist/: ${DIST_FILES.join(", ")}, ${emitTarball(json)}`);
}
process.exit(0);

function emitTarball(manifest) {
    const distDir = path.join(process.cwd(), "dist");
    // styles.css is copied asynchronously at the top of this file; make sure
    // it has landed before it goes into the archive.
    fs.copyFileSync("styles.css", path.join(distDir, "styles.css"));
    const tarball = `${manifest.id}-${manifest.version}.tar.gz`;
    // drop tarballs from previous versions so dist/ only ever has the current one
    for (const old of fs.readdirSync(distDir).filter((f) => f.endsWith(".tar.gz"))) {
        fs.rmSync(path.join(distDir, old));
    }
    cp.execFileSync("tar", [
        "-czf",
        path.join(distDir, tarball),
        "--owner=0",
        "--group=0",
        "--numeric-owner",
        "--sort=name",
        "-C",
        distDir,
        ...DIST_FILES
    ]);
    return tarball;
}
