on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        environment: runner
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  # this assumes that you have created a personal access token
                  # (PAT) and configured it as a GitHub action secret named
                  # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
                  token: ${{ secrets.GITHUB_TOKEN }}
                  # this is a built-in strategy in release-please, see "Action Inputs"
                  # for more options
                  release-type: node

            - uses: actions/checkout@v5

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "24.x"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: TypeCheck
              run: npm run type-check

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Build plugin
              run: npm run build
              env:
                  SYNCBUNDLEVERSION: ${{ steps.release.outputs.tag_name }}
                  LOKIACCESSCLIENTID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
                  LOKIACCESSCLIENTSECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

            - name: Update versions
              run: npm run version
              if: ${{ steps.release.outputs.release_created }}

            - name: push change release
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/parrajustin/obsidian-drive-sync.git"
                  git add -f manifest.json
                  git add -f versions.json
                  git commit -a -m 'ci: ${{ steps.release.outputs.tag_name }} update versions'
                  git push origin
              if: ${{ steps.release.outputs.release_created }}

            - name: Upload Release Artifact
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release upload ${{ steps.release.outputs.tag_name }} dist/main.js manifest.json styles.css
              if: ${{ steps.release.outputs.release_created }}
